name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: get paths
        run: |
          pwd
          ls
      - name: Generate list using Markdown
        run: |
           echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
