name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [push]

env:
  DOCKER_REPO: wuyfee/nacos-ci   # wuyfeedocker/nacos-ci
  DOCKER_REPO_B: wuyfeehub/nacos-ci
  TEST_REPO_NAME: Wuyunfan-BUPT/nacos-e2e
  VERSION: $(${{ github.event.pull_request.number || github.ref_name }}-$(uuidgen))
  


  
jobs:
  SetENV:
    runs-on: ubuntu-latest
    steps:
      - name: set version
        run: |
          echo "VERSION=${{ github.event.pull_request.number || github.ref_name }}-$(uuidgen)" >> $GITHUB_ENV
      - name: echo version
        run: |
           echo ${{ env.VERSION }}
  Explore-GitHub-Actions:
    needs: [SetENV]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: ["centos"]
        java-version: ["8"]
        DOCKER_REPO_ADDR: [ DOCKER_REPO_B , DOCKER_REPO ]
    steps:
      - name: set hello_here
        run: |
          hello_here=123
          echo hell
          echo "hello_there=456"  >> $GITHUB_ENV
      - name: print hello_here
        run: |
          echo ${hello_here}
          echo "hello_there=${hello_there}"
      - name: echo version
        run: |
           echo ${{ env.VERSION }}
      - name: Print IP Address
        run: |
          echo "hello"
          echo "Machine IP Address is $(curl -s https://api.ipify.org)"
      - name: test while
        run: |
          number=''
          count=5
          while [[ "$number" == "" && $count -gt 0 ]]
          do
            let "count--"
            echo ${count}
            number='ii'
          done
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Generate list using Markdown
        run: |
           cat README.md >> $GITHUB_STEP_SUMMARY
      - name: print github.repository
        run: |
          echo ${{ github.repository }}
      - name: print env.ENVIRONMENT_NAME
        run: |
          echo ${{ github.event_name }}
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
  Second-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: add Markdown2
        run: |
           cat README1.md >> $GITHUB_STEP_SUMMARY
      - name: print vars.ABC
        run: |
          echo ${{ vars.ABC }}
      - name: set vars.ABC
        run: |
          echo "oieyrr" >> $vars.ABC
          echo "wdwede" >> $ABC
          
