name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@main
        with:
          path: README.md,CHANGELOG.md,docs\doc1.md
          outputpath: out
