name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Generate list using Markdown
        run: |
           cat README.md >> $GITHUB_STEP_SUMMARY
      - name: print github.repository
        run: |
          echo ${{ github.repository }}
      - name: print env.ENVIRONMENT_NAME
        run: |
          echo ${{ github.event_name }}
  Second-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: add Markdown2
        run: |
           cat README1.md >> $GITHUB_STEP_SUMMARY
