name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [push]

env:
  DOCKER_REPO: wuyfeehub/nacos-ci
  TEST_REPO_NAME: Wuyunfan-BUPT/nacos-e2e
  VERSION: $(${{ github.event.pull_request.number || github.ref_name }}-$(uuidgen))
  
jobs:
  prejob:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "hello"
  e2e-java-test:
    if: ${{ success() }}
    name: Java e2e Test
    needs: [prejob]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        mode: ["cluster","standalone","standalone_auth"]
        version: ['pp', 'ss']
    steps:
      - name: java e2e test
        run: |
          echo "${{ github.run_id }}-${{ strategy.job-index }}"
          if [[ ${{ matrix.mode }} == "standalone"* ]];then
            if [[ ${{ matrix.mode }} = "standalone_auth" ]]; then
              echo "standalone_auth"
            else 
              echo "stabdlone"
            fi
          else
            echo "cluster"
          fi
          echo ${{ matrix.mode }}-${{ matrix.version }} 
          if [ ${{ matrix.mode }} = "cluster" ] && [ ${{ matrix.version }} = "ss" ];then
            exit 1
          else
            exit 0
          fi
  getresult:
    if: ${{ always() }}
    needs: [prejob, e2e-java-test]
    runs-on: ubuntu-latest
    steps:
      - name: echo result
        run: |
          echo ${{ needs.e2e-java-test.result }}
          echo ${{ needs.e2e-java-test.result }}
