name: PR-CI

on:
  pull_request:
    branches: [ main ]
env:
  GITHUB_STEP_SUMMARY: TEst
  MY_TEST: ${{ vars.EFG }}

jobs:
  printTest:
    name: print test
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo ${{ github.event.workflow_run.id }}
          echo ${{ github.event_name }}
      - name: print GITHUB_RUN_ID
        run: |
          echo ${{ github.run_id }}
      - name: print github.job
        run: |
          sleep 10
          echo ${{ github.job }}
      - name: set IS_END values
        run: |
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables/ABC -d '{"name":"ABC","value":"waiting"}'
  showResult:
    name: show result
    needs: [printTest]
    runs-on: ubuntu-latest
    steps:
      - name: show in summary
        run: |
          echo ${{ vars.ABC }}
          echo  ${{ vars.ABC }} >> $GITHUB_STEP_SUMMARY
      - name: print GITHUB_RUN_ID
        run: |
          echo ${{ github.run_id }}
      - name: print github.job
        run: |
          echo ${{ github.job }}
      - name: waitting result
        run: |
          values=`curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables | jq -r '.variables[] | select(.name == "ABC") | .value'`
          while [ ${values} == "waiting" ]
          do
            echo "${values}..."
            sleep 2
            values=`curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables | jq -r '.variables[] | select(.name == "ABC") | .value'`
          done
          echo ${values}
          echo  ${values} >> $GITHUB_STEP_SUMMARY
