name: PR-CI

on:
  pull_request:
    branches: [ main ]
env:
  GITHUB_STEP_SUMMARY: TEst
  MY_TEST: ${{ vars.EFG }}

jobs:
  printTest:
    name: print test
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo ${{ github.event.workflow_run.id }}
          echo ${{ github.event_name }}
      - name: print workflow id
        run: |
          echo ${{ github.event.workflow.id }}
      - name: print workflow job id
        run: |
          echo ${{ github.event.workflow_job.id }}
  showResult:
    name: show result
    runs-on: ubuntu-latest
    steps:
      - name: show in summary
        run: |
          echo ${{ vars.ABC }}
          echo  ${{ vars.ABC }} >> $GITHUB_STEP_SUMMARY
