name: PR-CI

on:
  pull_request:
    branches: [ main ]
env:
  GITHUB_STEP_SUMMARY: TEst

jobs:
  printTest:
    name: print test
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo ${{ github.event.workflow_run.id }}
          echo ${{ github.event_name }}
  showResult:
    name: show result
    runs-on: ubuntu-latest
    steps:
      - name: show in summary
        run: |
          echo ${{ env.MYVARIABLE }}
          echo ${{ vars.MYVARIABLE }}
          echo  ${{ vars.MYVARIABLE }}>> $GITHUB_STEP_SUMMARY
