name: PR-CI

on:
  pull_request:
    branches: [ main ]

jobs:
  printTest:
    name: print test
    runs-on: ubuntu-latest
    steps:
      - name: print github.job
        run: |
          sleep 10
          echo ${{ github.job }}
      - name: generate TEMP_VARI
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables -d "{\"name\":\"VARI_${{ github.run_id }}\",\"value\":\"waiting\"}"
#      - name: set IS_END values
#        run: |
#          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables/ABC -d '{"name":"ABC","value":"waiting"}'
  showResult:
    name: show result
    needs: [printTest]
    runs-on: ubuntu-latest
    steps:
      - name: print GITHUB_RUN_ID
        run: |
          echo ${{ github.run_id }}
      - name: print github.job
        run: |
          echo ${{ github.job }}
      - name: waitting result
        run: |
          values=`curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables | jq -r '.variables[] | select(.name == "VARI_${{ github.run_id }}") | .value'`
          while [ ${values} == "waiting" ]
          do
            echo "${values}..."
            sleep 2
            values=`curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables | jq -r '.variables[] | select(.name == "VARI_${{ github.run_id }}") | .value'`
          done
          echo ${values}
          echo  "https://github.com/Wuyunfan-BUPT/help/actions/runs/${values}" >> $GITHUB_STEP_SUMMARY
      - name: delete variables
        run: |
          curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables/VARI_${{ github.run_id }}
          
