name: PR-CI

on:
  pull_request:
    branches: [ main ]
env:
  GITHUB_STEP_SUMMARY: TEst
  MY_TEST: ${{ vars.EFG }}

jobs:
  printTest:
    name: print test
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo ${{ github.event.workflow_run.id }}
          echo ${{ github.event_name }}
      - name: print GITHUB_RUN_ID
        run: |
          echo ${{ github.run_id }}
      - name: print github.job
        run: |
          echo ${{ github.job }}
      - name: set IS_END values
        run: |
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables/IS_END -d '{"name":"IS_END","value":"FALSE"}'
  showResult:
    name: show result
    runs-on: ubuntu-latest
    steps:
      - name: show in summary
        run: |
          echo ${{ vars.ABC }}
          echo  ${{ vars.ABC }} >> $GITHUB_STEP_SUMMARY
      - name: print GITHUB_RUN_ID
        run: |
          echo ${{ github.run_id }}
      - name: print github.job
        run: |
          echo ${{ github.job }}
