name: E2E test for pull request


on:
  workflow_run:
    workflows: ["PR-CI"]
    types:
      - requested
jobs:
  RunIdReturn:
    runs-on: ubuntu-latest
    steps:
      - name: print workflow_run id
        run: |
          echo ${{ github.event.workflow_run.id }}
          pr_run_id=${{ github.event.workflow_run.id }}
          echo ${pr_run_id}
          job_id=`curl -s https://api.github.com/repos/Wuyunfan-BUPT/help/actions/runs/${pr_run_id}/jobs | jq -r '.jobs[] | select(.name == "show result") | .id'`
          echo ${job_id}
          echo ${{ github.run_id }}
          echo "curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables"
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables/ABC -d '{"name":"ABC","value": ${{ github.run_id }}}'
          echo "curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables"

          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/jobs/${job_id}/rerun
          
