name: E2E test for pull request


on:
  workflow_run:
    workflows: ["PR-CI"]
    types:
      - requested
env:
    BASE_RUN_URL: https://api.github.com/repos/Wuyunfan-BUPT/help/actions/runs
jobs:
  waitPr:
    runs-on: ubuntu-latest
    steps:
      - name: waiting pr-ci
        run: |
          pr_run_id=${{ github.event.workflow_run.id }}
          echo ${pr_run_id}
          status=`curl -s https://api.github.com/repos/Wuyunfan-BUPT/help/actions/runs/${pr_run_id}/jobs | jq -r '.jobs[] | select(.name == "print test") | .status'`
          echo ${status}
          while [ ${status} != "completed" ]
          do
            echo "waitting..."
            sleep 3
            status=`curl -s https://api.github.com/repos/Wuyunfan-BUPT/help/actions/runs/${pr_run_id}/jobs | jq -r '.jobs[] | select(.name == "print test") | .status'`
          done
  RunIdReturn:
    needs: [waitPr]
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && 'success' == `curl -s ${BASE_RUN_URL}/${{ github.event.workflow_run.id }}/jobs | jq -r '.jobs[] | select(.name == "print test") | .conclusion'` }}
    steps:
      - name: print workflow_run id
        run: |
          echo `curl -s ${BASE_RUN_URL}/${{ github.event.workflow_run.id }}/jobs | jq -r '.jobs[] | select(.name == "print test") | .conclusion'`
          echo ${{ github.event.workflow_run.id }}
          pr_run_id=${{ github.event.workflow_run.id }}
          echo ${pr_run_id}
          job_id=`curl -s https://api.github.com/repos/Wuyunfan-BUPT/help/actions/runs/${pr_run_id}/jobs | jq -r '.jobs[] | select(.name == "print test") | .id'`
          echo ${job_id}
          
          echo ${{ github.run_id }}
          runID=${{ github.run_id }}
          data="{\"name\",\"ABC\",\"value\": \"${runID}\"}"
          echo $data
        
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Wuyunfan-BUPT/help/actions/variables/VARI_${pr_run_id} -d "{\"name\": \"VARI_${pr_run_id}\",\"value\": \"${runID}\"}" 
