name: E2E test for pull request


on:
  workflow_run:
    workflows: ["PR-CI"]
    types:
      - completed
  
jobs:
  RunIdReturn:
    runs-on: ubuntu-latest
    steps:
      - name: print workflow id
        run: |
          echo ${{ github.event.workflow.id }}
      - name: print workflow job id
        run: |
          echo ${{ github.event.workflow_job.id }}
      - name: print workflow_run id
        run: |
          echo ${{ github.event.workflow_run.id }}
          echo ${{ github.event_name }}
