name: E2E test for pull request


on:
  workflow_run:
    workflows: ["PR-CI"]
    types:
      - completed
  

jobs:
  RunIdReturn:
    name: get run id
    runs-on: ubuntu-latest
    steps:
      - name: curl http
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" --data '{"event_type": "update-summary", "client_payload": {"run_id": "${{ github.event.inputs.runId }}"}}' https://api.github.com/repos/Wuyunfan-BUPT/help/dispatches
